[package]
name = "nnmf-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = {version = "0.32.4", features = ["rand"]}
ndarray = "0.15.6"
